builds:
  -
    id: "yopass-ng"
    binary: yopass-ng
    main: ./cmd/yopass-ng/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - netbsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: yopass-ng-binaries
    name_template: "yopass-ng-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "yopass-ng_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/yopass-ng
    maintainer: Michael Paepcke <git@paepcke.de>
    description: yopass-ng
    license: Apache 2.0 
    formats:
      - deb
      - rpm
