name: ghcr.io docker build
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions: 
       packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Log in to the Container registry
        uses: docker/login-action@latest
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@latest
        with:
          push: true
          tags: ghcr.io/paepckehh/yopass-ng:latest
